@startuml
class Person {
    -firstName
    -lastName

    +Person(firstName, lastName)
}

class Employee {
    -salary
}

class ParsingDataFiles{}

Person <|--Employee
ParsingDataFiles--Person
@enduml